const app  = require('./app');
const pool = require('./db/connection');

const PORT = process.env.PORT || 3000;

async function initDb() {
  const fs   = require('fs');
  const path = require('path');
  const sql  = fs.readFileSync(path.join(__dirname, 'db/schema.sql'), 'utf8');

  // Split on semicolons but ignore empty chunks
  const isCloud = !!(process.env.DATABASE_URL || process.env.MYSQL_URL || process.env.MYSQLHOST);
  const statements = sql
    .replace(/--.*$/gm, '')        // strip comments
    .split(';')
    .map(s => s.trim())
    .filter(s => s.length > 0)
    // Skip CREATE DATABASE / USE on cloud — DB already exists with a different name
    .filter(s => !isCloud || (!/^CREATE DATABASE/i.test(s) && !/^USE /i.test(s)));

  for (const stmt of statements) {
    try {
      await pool.query(stmt);
    } catch (err) {
      // Ignore "already exists" and duplicate errors during init
      if (!['ER_TABLE_EXISTS_ERROR', 'ER_DUP_ENTRY', 'ER_DUP_KEYNAME'].includes(err.code)) {
        console.warn('DB init warning:', err.message);
      }
    }
  }
  console.log('Database ready.');
}

async function migrateXp() {
  const q = (sql) => pool.query(sql).catch(() => {});
  await q(`ALTER TABLE users ADD COLUMN xp INT NOT NULL DEFAULT 0`);
  await q(`ALTER TABLE users ADD COLUMN level INT NOT NULL DEFAULT 1`);
  // Deduplicate quiz_questions then add unique constraint so INSERT IGNORE is idempotent
  await q(`DELETE q1 FROM quiz_questions q1 INNER JOIN quiz_questions q2 WHERE q1.id > q2.id AND q1.quiz_id = q2.quiz_id AND q1.sort_order = q2.sort_order`);
  await q(`ALTER TABLE quiz_questions ADD UNIQUE KEY uq_quiz_sort (quiz_id, sort_order)`);
  console.log('XP migration done.');
}

async function seedQuizData() {
  // Idempotent quiz seed — runs on every startup, INSERT IGNORE skips existing rows
  const q = (sql, params) => pool.query(sql, params).catch(e => console.warn('Seed warn:', e.message));

  // Ensure quizzes exist with correct duration
  const quizzes = [
    [1,'Cryptography Basics','Cybersecurity','Test your knowledge of encryption algorithms and cryptographic principles.','Easy',15],
    [2,'SQL Query Challenge','Databases','Challenge yourself with complex SQL queries and database design questions.','Medium',20],
    [3,'Web Security OWASP Top 10','Cybersecurity','How well do you know the most critical web application security risks?','Hard',25],
    [4,'Machine Learning Concepts','Data Science','Assess your understanding of ML algorithms, bias-variance tradeoff, and model selection.','Medium',20],
    [5,'Network Security Fundamentals','Cybersecurity','Test your knowledge of firewalls, VPNs, IDS/IPS, and network attack techniques.','Medium',20],
    [6,'Python for Data Science','Data Science','Assess your skills in NumPy, Pandas, Matplotlib, and scikit-learn workflows.','Medium',20],
    [7,'Cloud Computing & AWS','DevOps','Test your understanding of cloud concepts, core AWS services, and cloud security.','Medium',20],
    [8,'Full Stack Web Development','Web Dev','Cover REST APIs, Node.js, Express, SQL, JWT, and HTTP fundamentals.','Medium',20],
    [9,'React & Modern JavaScript','Web Dev','Test your knowledge of React hooks, the virtual DOM, ES6+ features, and state.','Medium',20],
  ];
  for (const row of quizzes) {
    await q('INSERT IGNORE INTO quizzes (id,title,subject,description,difficulty,duration_min) VALUES (?,?,?,?,?,?)', row);
    await q('UPDATE quizzes SET duration_min=? WHERE id=?', [row[5], row[0]]);
  }

  // All 90 questions — (quiz_id, question, a, b, c, d, correct, explanation, sort_order)
  const questions = [
    // ── Quiz 1: Cryptography ──────────────────────────────────────────────────
    [1,'What does AES stand for?','Advanced Encryption Standard','Applied Encryption System','Automated Encryption Software','Advanced Encoding Standard','A','AES (Advanced Encryption Standard) is a symmetric encryption algorithm widely used worldwide.',1],
    [1,'Which hashing algorithm produces a 256-bit hash?','MD5','SHA-1','SHA-256','SHA-512','C','SHA-256 produces a 256-bit (32-byte) hash value, commonly used in digital signatures and certificates.',2],
    [1,'What is the key length of AES-128?','64 bits','128 bits','192 bits','256 bits','B','AES-128 uses a 128-bit key, offering strong security for most applications.',3],
    [1,'Which is an asymmetric encryption algorithm?','AES','DES','RSA','Blowfish','C','RSA is an asymmetric algorithm using a public/private key pair.',4],
    [1,'What does a digital signature verify?','Encryption strength','Identity and integrity','Password complexity','Network speed','B','Digital signatures verify the authenticity of the sender and integrity of the message.',5],
    [1,'What does Perfect Forward Secrecy (PFS) guarantee?','Past session keys cannot be recovered even if the long-term private key is later compromised','Encrypted sessions are stored permanently on the server','Symmetric keys are the same for every session','The server private key rotates every 24 hours','A','PFS uses ephemeral (short-lived) key pairs per session. Even if the long-term key is stolen, past sessions cannot be decrypted because ephemeral keys are discarded after use.',6],
    [1,'Which AES mode provides both encryption AND authentication in a single operation?','ECB','CBC','CTR','GCM','D','GCM (Galois/Counter Mode) is an AEAD mode — it encrypts the data and produces an authentication tag in one pass, detecting any tampering.',7],
    [1,'What is a rainbow table attack?','A brute-force attack on wireless networks','Using precomputed hash-to-password mappings to crack unsalted password hashes','An attack exploiting weak IV reuse in AES-CBC','A technique to intercept TLS handshakes','B','Rainbow tables are precomputed tables of password-to-hash pairs. They crack unsalted hashes instantly. Adding a unique random salt per password defeats this attack entirely.',8],
    [1,'Which signature algorithm is deterministic (safe even with a bad random number generator)?','ECDSA','RSA-PKCS1 v1.5','EdDSA (Ed25519)','DSA','C','Ed25519 derives its per-signature nonce deterministically from the private key and message, so a faulty RNG cannot leak the private key. ECDSA failed catastrophically on the PS3 due to a constant nonce.',9],
    [1,"What is Kerckhoffs's principle?",'The key must be kept secret, but the algorithm can be public','Both the key and the algorithm must be kept secret','The plaintext must never exceed the key length','Encryption algorithms must be approved by a government authority','A','Kerckhoffs stated that a cryptosystem should be secure even if everything about it except the key is public. AES and RSA are fully open standards, yet secure because security rests on the key alone.',10],
    // ── Quiz 2: SQL ──────────────────────────────────────────────────────────
    [2,'Which SQL clause filters grouped results?','WHERE','HAVING','GROUP BY','ORDER BY','B','HAVING filters results after GROUP BY, while WHERE filters before grouping.',1],
    [2,'What does INNER JOIN return?','All rows from left table','All rows from right table','Only matching rows from both tables','All rows from both tables','C','INNER JOIN returns only rows where the join condition is met in both tables.',2],
    [2,'Which keyword removes duplicate rows in SELECT?','UNIQUE','DISTINCT','REMOVE','FILTER','B','SELECT DISTINCT eliminates duplicate rows from the result set.',3],
    [2,'What is a PRIMARY KEY?','A foreign reference','A unique non-null identifier','An indexed column','A default value','B','A PRIMARY KEY uniquely identifies each record and cannot be NULL.',4],
    [2,'Which function counts non-NULL values?','SUM()','COUNT()','AVG()','MAX()','B','COUNT() counts non-NULL values in a column when a column name is specified.',5],
    [2,'What is a deadlock in a database?','A query that takes too long to execute','Two transactions each waiting for a lock held by the other, creating a circular wait','A table with no primary key','An index that covers too many columns','B','A deadlock occurs when Transaction A holds a lock that Transaction B needs, while B holds a lock A needs. The database detects this and kills one transaction to break the cycle.',6],
    [2,'What does EXPLAIN do in SQL?','Runs a query and explains the result in plain English','Shows the query execution plan chosen by the database planner','Adds comments to a stored procedure','Validates the SQL syntax without executing the query','B','EXPLAIN shows how the database plans to execute a query — which indexes it will use, join order, and estimated row counts. Essential for identifying slow full table scans.',7],
    [2,'What is a covering index?','An index that spans the entire table','An index containing all columns required by a query so the table itself does not need to be read','A composite index on foreign key columns','An index automatically created by the database','B','A covering index satisfies a query entirely from the index structure, avoiding a second lookup in the actual table. This dramatically speeds up read-heavy queries.',8],
    [2,'Which SQL window function assigns a unique sequential integer to each row within a partition?','RANK()','DENSE_RANK()','ROW_NUMBER()','NTILE()','C','ROW_NUMBER() assigns 1, 2, 3, ... to each row within a partition with no gaps or ties. RANK() and DENSE_RANK() handle tied values differently.',9],
    [2,'What is the key difference between DELETE and TRUNCATE?','DELETE removes the table; TRUNCATE removes rows','TRUNCATE is faster, removes all rows without logging individual deletions; DELETE logs each row and supports WHERE','DELETE is DDL; TRUNCATE is DML','There is no difference','B','TRUNCATE deallocates data pages — very fast but cannot be rolled back in most databases and does not fire row-level triggers. DELETE is DML, supports WHERE, and logs each row.',10],
    // ── Quiz 3: Web Security ─────────────────────────────────────────────────
    [3,'What is SQL Injection?','A database design pattern','Inserting malicious SQL into inputs','A type of network attack','An SQL performance technique','B','SQL injection inserts malicious SQL code through user input to manipulate the database.',1],
    [3,'What does XSS stand for?','Extra Style Sheet','Cross-Site Scripting','Cross-Server Security','XML Style Script','B','XSS (Cross-Site Scripting) injects malicious scripts into web pages viewed by other users.',2],
    [3,'Which HTTP header prevents clickjacking?','Content-Type','X-Frame-Options','Accept-Encoding','Authorization','B','X-Frame-Options prevents your page from being embedded in iframes on other sites.',3],
    [3,'What is CSRF?','A type of SQL attack','Cross-Site Request Forgery','Content Security Response Framework','Client-Side Request Filter','B','CSRF tricks users into submitting requests they did not intend, exploiting their authenticated session.',4],
    [3,'Which is the safest way to store passwords?','Plain text','Base64 encoded','Hashed with bcrypt','MD5 hashed','C','bcrypt is a password-hashing function designed to be slow and resist brute-force attacks.',5],
    [3,'What does HSTS do?','Encrypts HTTP request bodies automatically','Forces the browser to use HTTPS for a domain for a defined period, even if HTTP is typed','Adds authentication headers to every HTTP request','Blocks third-party cookies','B','HSTS tells the browser to always connect to this domain over HTTPS, defeating SSL stripping attacks.',6],
    [3,'What is SSRF (Server-Side Request Forgery)?','A stored XSS attack targeting the server','An attack where the server is tricked into making HTTP requests to internal or unintended external targets','A SQL injection variant targeting NoSQL databases','A CSRF variant targeting API servers','B','In SSRF, an attacker supplies a URL that the server fetches on their behalf, often targeting internal services like the AWS metadata endpoint.',7],
    [3,'Which JWT algorithm should NEVER be accepted by a server?','HS256','RS256','ES256','none','D','The "none" algorithm means no signature. If a server accepts alg:none, an attacker can forge any token by removing the signature. Always whitelist accepted algorithms.',8],
    [3,'What is the purpose of a Content Security Policy (CSP) header?','To enforce HTTPS for all resources','To whitelist which sources scripts, styles, and other resources may be loaded from, blocking injected scripts','To prevent SQL injection attacks','To rate-limit API requests','B','CSP tells the browser which origins are trusted to serve scripts, styles, and fonts. An XSS payload cannot run if its origin is not in the CSP whitelist.',9],
    [3,'What is Broken Object Level Authorisation (BOLA)?','Failing to hash passwords correctly','Allowing users to access other users resources by simply changing an object ID in a request','Storing JWT secrets in plaintext','A misconfigured CORS policy','B','BOLA occurs when an API uses user-supplied IDs without verifying the requesting user owns that object. Always verify ownership server-side.',10],
    // ── Quiz 4: Machine Learning ─────────────────────────────────────────────
    [4,'What is overfitting?','Model performs well on all data','Model memorises training data, fails on new data','Model has too few parameters','Model trains too slowly','B','Overfitting occurs when a model learns noise from training data and fails to generalise.',1],
    [4,'Which algorithm is used for classification?','Linear Regression','K-Means','Logistic Regression','PCA','C','Logistic Regression predicts categorical outcomes, making it suitable for classification tasks.',2],
    [4,'What does the bias-variance tradeoff mean?','Speed vs accuracy','Underfitting vs overfitting balance','Training vs test split','Precision vs recall','B','High bias = underfitting; high variance = overfitting. The tradeoff is finding the right model complexity.',3],
    [4,'What is a confusion matrix used for?','Visualising neural networks','Evaluating classification performance','Hyperparameter tuning','Data normalisation','B','A confusion matrix shows true/false positives and negatives, summarising classification results.',4],
    [4,'Which technique reduces overfitting?','Adding more features','Removing training data','Regularisation','Increasing model size','C','Regularisation (L1/L2) penalises large weights, reducing overfitting by constraining model complexity.',5],
    [4,'What is the purpose of k-fold cross-validation?','To split the dataset into k equal training sets','To train k different models and pick the best','To produce a reliable performance estimate by training and evaluating on k different data splits','To reduce the number of features to k','C','k-fold CV trains on k-1 folds and tests on the remaining fold, repeated k times. Averaging the k scores gives a more reliable estimate than a single split.',6],
    [4,'What does PCA do?','Classifies data into principal groups','Reduces dimensionality by projecting data onto directions of greatest variance','Clusters data points using centroids','Increases the number of features to improve accuracy','B','PCA transforms features into uncorrelated components ordered by variance explained, reducing noise and training time.',7],
    [4,'What is gradient descent?','A method of selecting the steepest features','An iterative algorithm that adjusts model weights in the direction that reduces the loss function','A technique for normalising gradient values in neural networks','A cross-validation strategy for deep learning','B','Gradient descent computes the gradient of the loss with respect to each weight, then moves each weight a small step opposite the gradient, minimising loss iteratively.',8],
    [4,'What does the ROC-AUC score measure?','The accuracy of a regression model','How quickly a model trains','A classifier ability to distinguish between classes across all decision thresholds','The ratio of precision to recall','C','The ROC curve plots True Positive Rate vs False Positive Rate. AUC summarises this: 1.0 = perfect, 0.5 = random guessing.',9],
    [4,'What is the difference between bagging and boosting?','Bagging uses deep trees; boosting uses shallow stumps','Bagging trains models in parallel on random subsets to reduce variance; boosting trains sequentially to correct errors, reducing bias','Bagging is for classification only; boosting is for regression only','They are the same technique','B','Bagging (Random Forest) reduces variance. Boosting (XGBoost) trains each model to correct the residual errors of the ensemble so far, reducing bias.',10],
    // ── Quiz 5: Network Security ──────────────────────────────────────────────
    [5,'At which OSI layer does TLS operate?','Layer 2 (Data Link)','Layer 3 (Network)','Layer 4-5 (Transport/Session)','Layer 7 (Application)','C','TLS sits between the Transport layer (TCP) and the Application layer, providing a secure channel for protocols like HTTP and SMTP.',1],
    [5,'What does a stateful firewall track that a stateless packet filter does not?','Source IP addresses','MAC addresses','TCP connection state','Port numbers','C','A stateful firewall maintains a connection table tracking whether each packet is part of an established TCP session, blocking unsolicited inbound packets.',2],
    [5,'What is ARP spoofing?','Injecting false DNS records into a resolver cache','Sending fake ARP replies to associate the attacker MAC with a legitimate IP, enabling a man-in-the-middle attack','Flooding a switch with MAC addresses to disable MAC learning','Redirecting HTTP traffic to a rogue server','B','ARP has no authentication. An attacker can broadcast fake ARP replies poisoning the ARP caches of other hosts, redirecting their traffic through the attacker machine.',3],
    [5,'What is a DMZ in network architecture?','A VLAN reserved for wireless devices','A network segment between the internet and the internal network that hosts public-facing servers','An encrypted tunnel between two office locations','A firewall rule that blocks all inbound traffic','B','A DMZ places web servers and other public-facing services on a separate segment. If one is compromised, the attacker is isolated from the internal corporate network.',4],
    [5,'What is the primary function of an IDS?','Blocks malicious traffic in real time','Monitors and alerts on suspicious network activity or host behaviour','Manages SSL certificates for HTTPS','Encrypts traffic between network segments','B','An IDS monitors traffic for suspicious patterns and generates alerts. An IPS goes further and actively blocks detected threats.',5],
    [5,'What is DNS cache poisoning?','Overloading a DNS server with too many queries','Injecting forged DNS records into a resolver cache so domain names resolve to attacker-controlled IPs','Encrypting DNS queries to prevent eavesdropping','Registering a domain similar to a legitimate one','B','DNS has no authentication by default. An attacker can race to respond with a forged answer, poisoning the cache and redirecting users to a malicious server.',6],
    [5,'What security improvement does WPA3 provide over WPA2?','Longer SSID names','Simultaneous Authentication of Equals (SAE) replacing the PSK handshake, preventing offline dictionary attacks','Support for more simultaneous clients','Faster throughput via 802.11ax','B','WPA2 PSK handshakes can be captured and brute-forced offline. WPA3 SAE is interactive and zero-knowledge, so captured handshakes cannot be cracked offline.',7],
    [5,'What is the purpose of network segmentation?','To increase bandwidth between segments','To divide a network into zones so a compromise in one zone cannot easily spread to others','To route traffic more efficiently between VLANs','To hide internal IP addresses using NAT','B','Segmentation limits the blast radius of a breach. Critical systems like databases should be on isolated segments with strict firewall rules.',8],
    [5,'What does a SIEM system do?','Scans code for vulnerabilities before deployment','Aggregates and correlates logs from across the infrastructure to detect threats and support incident response','Encrypts log files to prevent tampering','Blocks intrusion attempts in real time','B','A SIEM (e.g., Splunk, Microsoft Sentinel) collects logs from firewalls, IDS, servers, and apps for centralised threat detection and hunting.',9],
    [5,'What is VPN split tunnelling?','A VPN that encrypts only the header not the payload','A configuration where only traffic to specific destinations routes through the VPN while other traffic uses the normal internet connection','Using two VPN tunnels simultaneously for redundancy','Splitting a site-to-site VPN into two half-tunnels','B','Split tunnelling routes only corporate traffic through the VPN while internet traffic goes directly out, reducing VPN load.',10],
    // ── Quiz 6: Python for Data Science ──────────────────────────────────────
    [6,'Which Python library provides the ndarray for fast numerical computing?','Pandas','Matplotlib','NumPy','SciPy','C','NumPy provides the ndarray — a fast, memory-efficient multi-dimensional array implemented in C, foundational to all Python data science libraries.',1],
    [6,'What does the Pandas groupby() operation do?','Sorts a DataFrame by one or more columns','Splits a DataFrame into groups, applies an aggregation function to each group, and combines the results','Joins two DataFrames on a common column','Removes duplicate rows from a DataFrame','B','groupby() implements split-apply-combine: split rows into groups by column value, apply a function (sum, mean, count), and combine into a new DataFrame.',2],
    [6,'What is data leakage in machine learning?','Training data accidentally deleted during preprocessing','Accidentally including future or target information during training, producing inflated performance metrics','Sensitive data being logged to a public server','Features with missing values causing errors during training','B','Data leakage occurs when test set information influences training — e.g., scaling the entire dataset before the train/test split. Always fit preprocessors on training data only.',3],
    [6,'What is feature scaling, and why is it important?','Reducing the number of features using PCA','Normalising feature ranges so no feature dominates the model due to its larger numerical magnitude','Selecting only the most correlated features for training','Converting categorical features to numerical ones','B','Algorithms like k-NN, SVM, and gradient descent are sensitive to feature magnitudes. Standardisation or min-max normalisation ensure all features contribute fairly.',4],
    [6,'What does NumPy broadcasting allow?','Sending NumPy arrays over a network socket','Performing arithmetic on arrays of different shapes without explicit loops, by automatically expanding smaller arrays','Distributing computation across multiple CPU cores','Converting Python lists to NumPy arrays','B','Broadcasting allows e.g. adding a row vector to every row of a matrix without a Python for-loop. The operation runs in optimised C.',5],
    [6,'What is the purpose of a train/test split?','To reduce training time by using less data','To evaluate how well a model generalises to unseen data by holding out a portion never seen during training','To balance classes in an imbalanced dataset','To create two copies of the data for backup','B','If you evaluate on the same data you trained on, the model appears perfect even if it memorised training data. The held-out test set simulates new unseen data.',6],
    [6,'Which chart type is most appropriate for visualising the distribution of a single numerical variable?','Bar chart','Scatter plot','Histogram','Line chart','C','A histogram bins continuous values and counts observations in each bin, showing the shape (normal, skewed, bimodal) of the distribution.',7],
    [6,'What does the Pandas .fillna() method do?','Removes rows with missing values','Fills missing (NaN) values with a specified value or strategy','Renames columns with null names','Replaces infinite values with NaN','B','NaN is Pandas representation of missing data. .fillna(value) replaces all NaN cells with a constant, mean, median, or forward/backward fill.',8],
    [6,'What does vectorisation mean in NumPy?','Converting string columns to numerical vectors','Replacing Python for-loops with array operations that execute in optimised C, orders of magnitude faster','Representing sparse matrices as dense vectors','Normalising data to unit vectors','B','Pure Python loops process one element at a time. NumPy vectorised operations process entire arrays in compiled C code, often 100-1000x faster for numerical tasks.',9],
    [6,'What is the scikit-learn Pipeline object used for?','Running multiple ML models in parallel','Chaining preprocessing steps and a model into a single object to prevent data leakage during cross-validation','Downloading datasets from the internet','Visualising the model training process','B','A Pipeline ensures fit() is called only on training data and transform() is applied consistently, preventing leakage of test set statistics into training.',10],
    // ── Quiz 7: Cloud Computing & AWS ────────────────────────────────────────
    [7,'What does IAM stand for in AWS?','Internet Access Management','Identity and Access Management — controls who can do what in your AWS account','Instance Allocation Monitor','Integrated Application Manager','B','Every API call in AWS is authorised by IAM. You create users, groups, and roles with attached policies that grant or deny specific permissions on specific resources.',1],
    [7,'What is the principle of least privilege in cloud security?','Giving all developers admin access for productivity','Granting only the minimum permissions required for a task — nothing more','Using the cheapest AWS instance types','Keeping all data in one region for simplicity','B','The most common cause of cloud data breaches is over-privileged IAM entities. Least privilege limits blast radius — a compromised credential can only access what it needed.',2],
    [7,'What AWS service provides scalable, durable object storage?','EBS (Elastic Block Store)','RDS (Relational Database Service)','S3 (Simple Storage Service)','EFS (Elastic File System)','C','S3 stores objects in buckets. It is designed for 99.999999999% durability, scales to exabytes, and is used for static websites, backups, data lakes, and file storage.',3],
    [7,'What does an AWS Security Group do?','Scans EC2 instances for malware','Acts as a stateful virtual firewall controlling inbound and outbound traffic to EC2 instances','Groups IAM users for permission management','Monitors AWS costs and sends budget alerts','B','Security Groups are stateful — inbound rules allow traffic, and return traffic is automatically allowed. All traffic is denied by default.',4],
    [7,'What is AWS Lambda?','A serverless compute service that runs code in response to events without you provisioning servers','A managed Kubernetes service','A NoSQL database','A content delivery network','A','Lambda runs your function only when triggered, scales from zero to thousands of concurrent executions, and charges per 100ms of execution time.',5],
    [7,'What is the difference between a public subnet and private subnet in a VPC?','Public subnets are faster; private subnets are more secure','Public subnets have a route to an Internet Gateway and can have public IPs; private subnets use a NAT Gateway for outbound traffic','Public subnets run web servers; private subnets run databases by convention only','There is no functional difference','B','Resources in a public subnet can receive inbound internet traffic. Private subnet resources are not directly reachable from the internet — they use NAT Gateway for outbound connections.',6],
    [7,'What does Multi-AZ deployment provide in AWS RDS?','Lower cost by spreading load','Automatic failover to a synchronous standby in a second Availability Zone if the primary fails','Read scaling through replicas','Automated database schema migrations','B','Multi-AZ maintains a synchronous replica in a different AZ. If the primary fails, RDS automatically fails over to the standby within 1-2 minutes with no data loss.',7],
    [7,'What is an AMI (Amazon Machine Image)?','An auto-scaling policy for EC2','A template containing the OS, software configuration, and data used to launch EC2 instances','An IAM permission policy for ML workloads','A monitoring agent installed on EC2 instances','B','AMIs are blueprints for EC2 instances. Create a custom AMI from a configured instance and use it to launch identical copies — essential for auto-scaling.',8],
    [7,'What is the shared responsibility model in cloud computing?','The cloud provider is responsible for all security','The customer is responsible for all security','The cloud provider secures the infrastructure; the customer is responsible for security of what runs on it','Security responsibilities are negotiated case by case','C','AWS secures physical infrastructure, hypervisor, and managed service internals. You are responsible for OS patching, IAM, network settings, application security, and data encryption.',9],
    [7,'What is auto-scaling in AWS?','Automatically upgrading EC2 instance types','Automatically adding or removing EC2 instances based on demand metrics to maintain performance and reduce cost','Automatically applying OS patches to EC2','Automatically backing up RDS databases','B','Auto Scaling Groups monitor CloudWatch metrics (CPU, request count). When demand rises, new instances launch. When it drops, excess instances terminate. You pay only for what you use.',10],
    // ── Quiz 8: Full Stack Web Development ───────────────────────────────────
    [8,'What HTTP method is conventionally used to fully replace a resource?','POST','PATCH','PUT','DELETE','C','PUT replaces the entire resource with the supplied body. PATCH updates only the specified fields. POST creates a new resource.',1],
    [8,'What is a middleware function in Express.js?','A function that compresses the final HTML response','A function with (req, res, next) that can inspect or modify the request, send a response, or call next() to pass control to the next handler','A helper library for database queries','A route handler for the root path','B','Middleware runs in a pipeline. Common examples: body-parser, cors(), authentication checks, logging. Calling next() passes control; not calling it ends the pipeline.',2],
    [8,'What are the three parts of a JWT?','Header (algorithm), Payload (claims like user ID), and Signature (verifies integrity)','Salt, hash, and version','Host, port, and credentials','Header, data, and expiry','A','JWTs are Base64-encoded JSON: header.payload.signature. The server verifies the signature cryptographically without a database lookup.',3],
    [8,'Why is bcrypt preferred over SHA-256 for password storage?','bcrypt compresses passwords; SHA-256 encrypts them','bcrypt is deliberately slow and salt-generating — SHA-256 is too fast, allowing billions of guesses per second on a GPU','bcrypt is reversible for password recovery; SHA-256 is not','There is no meaningful difference','B','Password hashing must be slow by design. bcrypt cost factor makes each hash take ~100ms, limiting an attacker to ~10 guesses/second instead of billions.',4],
    [8,'What does CORS control?','Which HTTP methods a server supports','Which cross-origin domains are allowed to make requests to an API via browser JavaScript','How compressed responses are encoded','Which cookies are sent with every request','B','Browsers enforce the Same-Origin Policy. The server opts in to cross-origin requests by sending Access-Control-Allow-Origin headers listing trusted origins.',5],
    [8,'What is the difference between authentication and authorisation?','They are the same concept with different names','Authentication verifies WHO you are (login); authorisation verifies WHAT you are allowed to do (permissions)','Authentication is for APIs; authorisation is for web pages','Authentication uses passwords; authorisation uses tokens','B','You must authenticate before you can be authorised. Checking if a user is logged in is auth; checking if they own the resource they are accessing is authz.',6],
    [8,'What is a database connection pool?','A backup copy of the database','A cache of reusable database connections that avoids the overhead of opening a new TCP connection per request','A query result cache','A pool of read replicas for load balancing','B','Opening a new DB connection is expensive (~20-100ms). A pool keeps connections open and reuses them across requests, drastically improving throughput.',7],
    [8,'Which HTTP status code should a REST API return when a resource is successfully created?','200 OK','201 Created','204 No Content','202 Accepted','B','201 Created signals that the POST request succeeded and a new resource was created. The response body typically includes the created object.',8],
    [8,'Why should secrets be stored in environment variables, not source code?','Environment variables are faster to read','Secrets committed to git persist in history forever and are exposed to anyone with repo access; env vars keep them out of version control','Environment variables are encrypted by default','Source code cannot store strings longer than 255 characters','B','Committing secrets to git is one of the most common security incidents. Use dotenv locally and the hosting platform config in production.',9],
    [8,'What is the N+1 query problem?','Running N queries to create a single record across N tables','Fetching a list of N records and then running a separate database query for each one, totalling N+1 queries instead of 1','Having more database indexes than table columns','A query that returns N+1 rows due to a faulty JOIN','B','Example: fetch 100 users (1 query), then for each user fetch their posts (100 queries) = 101 queries. Fix with a single JOIN or ORM eager loading.',10],
    // ── Quiz 9: React & Modern JavaScript ────────────────────────────────────
    [9,'What is JSX in React?','A JavaScript XML parser','A syntax extension that lets you write HTML-like code inside JavaScript, compiled to React.createElement() calls','A CSS-in-JS library','A JSON serialisation format for components','B','JSX is syntactic sugar. <div className="card">Hello</div> compiles to React.createElement("div",{className:"card"},"Hello"). Babel/Vite transpiles JSX before it runs in the browser.',1],
    [9,'What does the useEffect hook do?','Creates a new state variable','Runs a side effect after the component renders, with an optional cleanup function — replaces componentDidMount and componentDidUpdate','Memoises a function reference between renders','Creates a context provider','B','useEffect runs after every render by default. The dependency array controls when it re-runs. Return a cleanup function to cancel subscriptions or timers on unmount.',2],
    [9,'What is the virtual DOM in React?','A DOM stored in a database','An in-memory JavaScript representation of the UI that React uses to calculate the minimum set of real DOM updates needed','A hidden iframe used for rendering','A server-side copy of the DOM for SSR','B','When state changes, React re-renders into a new virtual DOM tree, diffs it against the previous one, and applies only the changed operations to the actual DOM.',3],
    [9,'What does useState return?','The current state value only','An array of [currentStateValue, setterFunction] — the setter triggers a re-render when called with a new value','A mutable ref object','A Promise that resolves to the state value','B','const [count, setCount] = useState(0). Calling setCount(1) triggers a re-render with the new value. Direct mutation does NOT trigger re-render.',4],
    [9,'What is a closure in JavaScript?','A syntax for immediately invoked functions','A function that retains access to variables from its outer scope even after that outer function has returned','A method for closing WebSocket connections','A design pattern for encapsulating class methods','B','Closures are fundamental to JS: event handlers, React hooks, module patterns all rely on them. They are why useState works correctly across renders.',5],
    [9,'What does the JavaScript spread operator (...) do?','Defines rest parameters in function signatures only','Expands an iterable (array/object) into individual elements — enables shallow copying and merging without mutation','Converts a string to a character array','Creates a generator function','B','const newArr = [...arr1, ...arr2] merges arrays. const newObj = {...obj, key: val} shallow-copies and overrides a key. Used in React to update state immutably.',6],
    [9,'What is the JavaScript event loop?','A built-in loop for handling DOM click events','The mechanism allowing single-threaded JS to handle async operations by moving completed callbacks from the task queue to the call stack when it is empty','A loop that runs every frame for animations','A Node.js-specific feature not present in browsers','B','JS is single-threaded. When you fetch() data, the browser handles I/O separately. The callback runs only when the call stack is empty, so async operations never block the UI.',7],
    [9,'What is React Context used for?','Managing component-level local state','Sharing state across multiple components in a tree without passing props through every intermediate level (prop drilling)','Fetching data from an API','Replacing all useState hooks in a large application','B','Context provides a way to pass values like theme or auth user to deeply nested components without explicit prop passing at every level.',8],
    [9,'What is destructuring assignment in JavaScript?','Removing properties from an object permanently','A syntax for extracting values from arrays or properties from objects into distinct variables in a single statement','Converting a class instance to a plain object','A method for deep-cloning objects','B','const {name, age} = user extracts object properties. const [first, second] = arr extracts array items. Used everywhere in React: const [state, setState] = useState().',9],
    [9,'What problem does async/await solve compared to raw Promises?','It makes JavaScript multi-threaded','It makes asynchronous code read like synchronous code, eliminating nested .then() chains while still being non-blocking','It eliminates the need for error handling','It speeds up network requests','B','async/await is syntactic sugar over Promises. await pauses the async function until the Promise resolves without blocking the thread. try/catch handles rejections naturally.',10],
    // ── Extra 5 per quiz (sort_order 11-15) ──────────────────────────────────
    [1,'What is the purpose of an IV (Initialisation Vector)?','To increase key length','To ensure identical plaintexts encrypt to different ciphertexts each time','To authenticate the sender','To compress the ciphertext','B','An IV is a random value combined with the key so the same plaintext encrypted twice produces different ciphertexts. It does not need to be secret but must be unique per message.',11],
    [1,'What is the difference between encoding and encryption?','No difference — both protect data','Encoding transforms format with no secret key; encryption requires a key for confidentiality','Encoding is faster than encryption','Encryption is reversible; encoding is not','B','Base64 encoding is not a security measure — anyone can decode it. Encryption uses a key to make data confidential. Never confuse the two.',12],
    [1,'What makes a hash function collision-resistant?','A very long output','It is computationally infeasible to find two different inputs that produce the same hash output','It uses symmetric keys','It can only be computed once per input','B','Collision resistance means an attacker cannot find x and y where H(x) = H(y). MD5 and SHA-1 are broken; SHA-256 and SHA-3 remain secure.',13],
    [1,'What is a padding oracle attack?','An attack on RSA key generation','Exploiting error messages about incorrect padding to decrypt CBC ciphertext byte-by-byte without the key','A brute-force attack on AES-ECB','An attack on TLS certificate validation','B','Padding oracle attacks exploit the application\'s reaction to invalid PKCS#7 padding. By sending crafted ciphertexts and observing success/failure, attackers recover the full plaintext.',14],
    [1,'What is the main advantage of ECC over RSA?','ECC is symmetric; RSA is asymmetric','ECC achieves equivalent security with much smaller key sizes, reducing computation and bandwidth','ECC does not require key generation','ECC is quantum-safe by default','B','A 256-bit ECC key provides comparable security to a 3072-bit RSA key — faster handshakes, less CPU, lower bandwidth.',15],
    [2,'What does a window function do differently than GROUP BY?','Window functions are faster','Window functions compute values across related rows without collapsing them into one row per group','Window functions only work on sorted data','Window functions replace the WHERE clause','B','GROUP BY reduces rows to one per group. Window functions (OVER clause) keep all rows and attach computed values — enabling running totals, ranking, moving averages.',11],
    [2,'What is the difference between UNION and UNION ALL?','UNION is faster','UNION removes duplicate rows; UNION ALL retains all rows including duplicates and is faster','UNION ALL requires a matching ORDER BY','UNION and UNION ALL are identical','B','UNION performs DISTINCT on the combined result. If you know there are no duplicates or want them, UNION ALL is always faster.',12],
    [2,'What is referential integrity?','A type of SQL index','A constraint ensuring every foreign key value references an existing primary key, preventing orphaned rows','A normalisation technique','A transaction isolation level','B','Foreign key constraints enforce referential integrity at the DB level. Inserting a non-existent foreign key or deleting a parent with children raises an error.',13],
    [2,'What is a correlated subquery?','A subquery using a JOIN','A subquery that references columns from the outer query and is re-evaluated for each outer row','A subquery inside a FROM clause','A subquery returning multiple columns','B','Correlated subqueries are often slow because they run once per outer row. Rewrite as a JOIN or window function for better performance.',14],
    [2,'What does COALESCE() return?','The maximum of its arguments','The first non-NULL value from its argument list','A concatenation of all arguments','NULL if any argument is NULL','B','COALESCE(a, b, c) returns the first non-NULL argument. Useful for fallback values: COALESCE(nickname, first_name, "Unknown").',15],
    [3,'What is SSRF (Server-Side Request Forgery)?','A type of XSS attack','Tricking the server into making HTTP requests to internal resources on behalf of the attacker','A client-side script injection','An attack on session cookies','B','SSRF exploits server-side URL fetching to reach internal services like metadata APIs or databases not publicly accessible.',11],
    [3,'What is IDOR (Insecure Direct Object Reference)?','A misconfigured HTTP header','Accessing another user\'s resource by guessing or modifying a reference ID in the request without authorisation checks','A type of SQL injection','A broken cryptographic function','B','IDOR occurs when apps expose internal IDs without verifying ownership. Fix: always verify the requesting user owns the resource on the server.',12],
    [3,'What is the purpose of HSTS?','To force HTTP connections','To instruct browsers to only connect via HTTPS for a specified duration, preventing downgrade attacks','To encrypt cookie values','To block mixed content','B','HSTS tells the browser never to connect over plain HTTP. Prevents SSL stripping attacks that downgrade HTTPS to HTTP.',13],
    [3,'What is a WAF (Web Application Firewall)?','A network-layer firewall','A tool that filters HTTP traffic to detect and block attacks like SQLi and XSS before they reach the app','An application performance monitor','A static code analysis tool','B','WAFs apply rule sets to incoming requests blocking known attack patterns while letting legitimate traffic through.',14],
    [3,'What is directory traversal?','Listing all files in a directory','Using ../ sequences in user input to escape the web root and read arbitrary server files','Brute-forcing file names','Exploiting symbolic links','B','Path traversal (../../etc/passwd) reads files outside the web directory. Fix: validate paths, strip traversal sequences, run server with minimal permissions.',15],
    [4,'What is the difference between classification and regression?','No difference','Classification predicts discrete categories; regression predicts continuous numeric values','Classification always uses neural networks','Regression is only for time-series','B','Spam detection is classification. House price prediction is regression. Output type determines algorithms and loss functions.',11],
    [4,'What is feature scaling and why is it needed?','Removing irrelevant features','Normalising feature ranges so distance-based algorithms are not dominated by large-scale features','Selecting the most important features','Encoding categorical variables','B','k-NN and SVMs use Euclidean distance. Features with large ranges dominate. StandardScaler (z-score) or MinMaxScaler fixes this.',12],
    [4,'What does AUC-ROC measure?','Model training speed','The classifier\'s ability to discriminate between classes across all thresholds, from 0.5 (random) to 1.0 (perfect)','Number of features selected','Training data size','B','The ROC curve plots TPR vs FPR at every threshold. AUC summarises this: 0.5 = random guessing, 1.0 = perfect separation.',13],
    [4,'What is regularisation in machine learning?','Adding more training data','Adding a penalty for model complexity to the loss function to reduce overfitting','Standardising feature scales','Removing outliers','B','L1 (Lasso) adds absolute coefficient sum — drives some to zero. L2 (Ridge) adds squared values — shrinks all towards zero.',14],
    [4,'What is the curse of dimensionality?','Running out of compute power','As dimensions increase, data becomes exponentially sparse making distance-based models unreliable','Too many training samples','A type of overfitting','B','In high dimensions all points become roughly equidistant, making nearest-neighbour algorithms meaningless. PCA and UMAP reduce dimensions while preserving structure.',15],
    [5,'What is a man-in-the-middle (MITM) attack?','Overloading a server with traffic','An attacker secretly intercepts and optionally alters communications between two parties who think they are communicating directly','Injecting code into a database','Brute-forcing a password','B','MITM attacks exploit unencrypted traffic or use ARP/DNS poisoning. Certificate pinning and TLS defend against them.',11],
    [5,'What does least privilege mean in networking?','Every user has admin rights','Users and systems have access only to the minimum network resources required for their function','All ports are open by default','All traffic is always encrypted','B','Least privilege limits breach blast radius. A compromised account with read-only access to one service cannot pivot to others.',12],
    [5,'What is a honeypot in network security?','A firewall rule set','A decoy system designed to lure attackers, detect intrusions, and gather intelligence','A password manager','A type of VPN','B','Any traffic to a honeypot is inherently suspicious. It provides early warning and reveals attacker techniques without risk to production systems.',13],
    [5,'What is the purpose of network segmentation?','To increase speed','To isolate network zones so a breach in one segment cannot freely spread to others, limiting lateral movement','To reduce IP addresses','To simplify firewalls','B','Segmentation uses VLANs and firewalls to create boundaries. A compromised IoT device on a guest VLAN cannot reach the corporate DB on a production VLAN.',14],
    [5,'What is ARP poisoning?','Flooding a switch with fake MACs','Sending fake ARP replies associating the attacker\'s MAC with a legitimate IP to redirect traffic through the attacker','A DNS cache poisoning variant','A wireless deauth attack','B','ARP has no authentication. An attacker on the same LAN can poison ARP tables of victims and the gateway, enabling MITM attacks.',15],
    [6,'What does a Python list comprehension do?','Removes matching items','Creates a new list by applying an expression to each element of an iterable, optionally filtered','Modifies a list in place','Sorts and deduplicates a list','B','[x**2 for x in range(10) if x%2==0] builds a list of even squares. Comprehensions are faster than equivalent for-loop append patterns.',11],
    [6,'What is the difference between shallow copy and deep copy in Python?','No practical difference','A shallow copy shares references to nested objects; deep copy recursively copies all nested objects independently','Shallow copy only works on lists','Deep copy is always slower','B','copy.copy() vs copy.deepcopy(). Modifying a nested list in a shallow copy also affects the original. deepcopy() breaks this link.',12],
    [6,'What does df.groupby() do in pandas?','Merges two DataFrames','Splits the DataFrame into groups by column value, enabling aggregates like sum(), mean(), count() on each group','Sorts the DataFrame','Drops duplicate rows','B','df.groupby("category")["revenue"].sum() gives total revenue per category. The result is indexed by the grouping column.',13],
    [6,'What is broadcasting in NumPy?','Converting arrays to lists','Performing operations between arrays of different shapes by automatically expanding the smaller array along missing dimensions','Saving an array to disk','Visualising array values','B','NumPy stretches smaller shapes without data copies: a 1D array + a column vector produces a 2D result, enabling efficient computation.',14],
    [6,'What is a Python generator?','A function returning a full list','A function using yield that produces values lazily one at a time, suspending and resuming, saving memory for large sequences','A class generating random numbers','A type of list comprehension','B','Generators are ideal for large datasets: yield produces one item at a time instead of building a million-element list in RAM.',15],
    [7,'What is an IAM role in AWS?','A user account with a password','An AWS identity with policies that can be assumed by services or users with no long-term credentials stored','A group of IAM users','A type of API key','B','Roles use temporary credentials via STS. Best practice: attach roles to EC2/Lambda rather than embedding access keys in code.',11],
    [7,'What is Amazon CloudFront?','A managed DNS service','A CDN that caches content at global edge locations to reduce latency for end users','A relational database','A private networking service','B','CloudFront sits in front of your origin (S3, ALB). Requests are served from the nearest edge instead of your origin server, reducing latency globally.',12],
    [7,'What is the difference between horizontal and vertical scaling?','They are the same','Horizontal scaling adds more instances (scale out); vertical scaling upgrades instance size (scale up) — horizontal is preferred for resilience','Horizontal only works for databases','Vertical is always cheaper','B','Horizontal scaling has no single point of failure, scales elastically, and enables zero-downtime deployments. Vertical scaling has a hard ceiling.',13],
    [7,'What is Infrastructure as Code (IaC)?','Documenting infrastructure manually','Defining and provisioning infrastructure through machine-readable code enabling repeatability and version control','Running scripts on servers manually','A cost estimation method','B','IaC (CloudFormation, Terraform) eliminates manual console clicks that drift from documentation. Version-control your infrastructure like application code.',14],
    [7,'What is a stateless application and why does it matter?','An app with no frontend','An app storing no session data on the instance, allowing any instance to serve any request and enabling auto-scaling','An app without a database','An app using only static files','B','Stateless apps store session data in Redis or JWTs. Any instance can serve any user — auto-scaling can freely add or remove instances.',15],
    [8,'What is a RESTful convention for resource URLs?','Use verb-based URLs like /getUser','Use noun-based resource URLs with HTTP methods (GET POST PUT DELETE) to express actions on resources','Use query strings for all params','Use POST for all operations','A','REST: GET /users fetches all, POST /users creates one, PUT /users/5 replaces one, DELETE /users/5 removes one. Methods are verbs; URLs are nouns.',11],
    [8,'Why should secrets never be committed to git?','Git repos are public by default','Secrets in git history persist forever and are visible to anyone with repo access, even after deletion from the latest commit','Git cannot store strings over 255 chars','Env vars are faster to read','B','Even in a private repo, secrets persist in git history. Use .env locally (in .gitignore) and platform environment variables in production.',12],
    [8,'What is the purpose of database connection pooling?','Backing up connections','Reusing a cache of open connections across requests to avoid the expensive overhead of opening a new TCP/auth connection per request','Encrypting database traffic','Load-balancing databases','B','Opening a DB connection takes 20-100ms. A pool keeps 10-20 connections open and hands them to requests in microseconds.',13],
    [8,'What is the difference between authentication and authorisation?','They are the same','Authentication verifies who you are (identity); authorisation verifies what you are allowed to do (permissions)','Auth is for APIs; authz for UIs','Auth uses tokens; authz uses passwords','B','Authn: "Are you really Alice?" Authz: "Is Alice allowed to delete this record?" You must authenticate before you can be authorised.',14],
    [8,'What HTTP status code should a successful POST creating a resource return?','200 OK','204 No Content','201 Created','302 Found','C','201 Created signals the request succeeded and a new resource was created. Best practice: return the created object with a Location header.',15],
    [9,'What is the difference between null and undefined in JavaScript?','They are identical','undefined means a variable was declared but never assigned; null is an intentional explicit absence of value','undefined is an error; null is normal','null is for numbers; undefined is for strings','B','typeof undefined === "undefined"; typeof null === "object" (historical JS bug). Functions return undefined by default. null == undefined is true with loose equality.',11],
    [9,'What is React reconciliation?','Fetching data from a server','The process of diffing the new virtual DOM against the previous one to compute the minimal set of real DOM operations to apply','Rendering on the server','Syncing state with a database','B','Keys help React identify list items correctly during diffing. Without keys, React may re-render or reorder DOM nodes unnecessarily.',12],
    [9,'Why must list items in React have a key prop?','Keys are used for styling','Keys let React identify which items changed, were added, or removed during reconciliation, enabling efficient list updates','Keys control render order','Keys are required for event handlers','B','Without stable unique keys, React cannot diff list changes efficiently — it may destroy and recreate nodes unnecessarily. Never use array index for dynamic lists.',13],
    [9,'What is code splitting in React?','Splitting CSS from JS','Dividing the JS bundle into smaller chunks loaded on demand with React.lazy and Suspense, reducing initial load time','Separating components into files','Using multiple entry points','B','React.lazy(() => import("./Dashboard")) loads the component bundle only when that component is first rendered, wrapped in Suspense for a loading fallback.',14],
    [9,'What is a pure function and why do React components prefer them?','A function with no parameters','A function that always returns the same output for the same inputs and has no side effects, making it predictable and testable','A function using only primitives','A function that never throws','B','Pure components are predictable: same props always produce the same UI. Side effects belong in useEffect. Impure components are hard to test and debug.',15],
  ];

  for (const [quiz_id, question, a, b, c, d, correct, explanation, sort_order] of questions) {
    await q(
      'INSERT IGNORE INTO quiz_questions (quiz_id,question,option_a,option_b,option_c,option_d,correct_answer,explanation,sort_order) VALUES (?,?,?,?,?,?,?,?,?)',
      [quiz_id, question, a, b, c, d, correct, explanation, sort_order]
    );
  }
  console.log('Quiz data seeded.');
}

initDb()
  .then(migrateXp)
  .then(seedQuizData)
  .then(() => app.listen(PORT, () => console.log(`StudyNest running on port ${PORT}`)))
  .catch(err => { console.error('Startup failed:', err.message); process.exit(1); });
