require('dotenv').config();
const pool = require('./connection');

(async () => {
  // ── Update durations now that quizzes have 10 questions ──────────────────────
  await pool.query(`UPDATE quizzes SET duration_min = 15 WHERE id = 1`);
  await pool.query(`UPDATE quizzes SET duration_min = 20 WHERE id = 2`);
  await pool.query(`UPDATE quizzes SET duration_min = 25 WHERE id = 3`);
  await pool.query(`UPDATE quizzes SET duration_min = 20 WHERE id = 4`);

  // ── Add 5 new quizzes ─────────────────────────────────────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quizzes (id, title, subject, description, difficulty, duration_min) VALUES
    (5, 'Network Security Fundamentals', 'Cybersecurity',  'Test your knowledge of firewalls, VPNs, IDS/IPS, and network attack techniques.', 'Medium', 20),
    (6, 'Python for Data Science',       'Data Science',   'Assess your skills in NumPy, Pandas, Matplotlib, and scikit-learn workflows.',     'Medium', 20),
    (7, 'Cloud Computing & AWS',         'DevOps',         'Test your understanding of cloud concepts, core AWS services, and cloud security.', 'Medium', 20),
    (8, 'Full Stack Web Development',    'Web Dev',        'Cover REST APIs, Node.js, Express, SQL, JWT, and HTTP fundamentals.',               'Medium', 20),
    (9, 'React & Modern JavaScript',     'Web Dev',        'Test your knowledge of React hooks, the virtual DOM, ES6+ features, and state.',    'Medium', 20)
  `);

  // ── Extra questions for Quiz 1: Cryptography (sort_order 6–10) ───────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (1,'What does Perfect Forward Secrecy (PFS) guarantee?',
       'Past session keys cannot be recovered even if the long-term private key is later compromised',
       'Encrypted sessions are stored permanently on the server',
       'Symmetric keys are the same for every session',
       'The server private key rotates every 24 hours',
       'A',
       'PFS uses ephemeral (short-lived) key pairs per session. Even if the long-term private key is stolen, past sessions cannot be decrypted because those ephemeral keys are gone.',
       6),
    (1,'Which AES mode provides both encryption AND authentication in a single operation?',
       'ECB','CBC','CTR','GCM',
       'D',
       'GCM (Galois/Counter Mode) is an AEAD mode — it encrypts the data and produces an authentication tag in one pass, detecting any tampering.',
       7),
    (1,'What is a rainbow table attack?',
       'A brute-force attack on wireless networks',
       'Using precomputed hash-to-password mappings to crack unsalted password hashes',
       'An attack exploiting weak IV reuse in AES-CBC',
       'A technique to intercept TLS handshakes',
       'B',
       'Rainbow tables are precomputed tables of password→hash pairs. They crack unsalted hashes instantly. Adding a unique random salt per password defeats this attack entirely.',
       8),
    (1,'Which signature algorithm is deterministic (safe even with a bad random number generator)?',
       'ECDSA','RSA-PKCS1 v1.5','EdDSA (Ed25519)','DSA',
       'C',
       'Ed25519 (EdDSA) derives its per-signature nonce deterministically from the private key and message, so a faulty RNG cannot leak the private key. ECDSA failed catastrophically on the PS3 due to a constant nonce.',
       9),
    (1,'What is Kerckhoffs''s principle?',
       'The key must be kept secret, but the algorithm can be public',
       'Both the key and the algorithm must be kept secret',
       'The plaintext must never exceed the key length',
       'Encryption algorithms must be approved by a government authority',
       'A',
       'Kerckhoffs stated that a cryptosystem should be secure even if everything about it except the key is public. Modern algorithms like AES and RSA are fully open, yet secure because the security rests on the key alone.',
       10)
  `);

  // ── Extra questions for Quiz 2: SQL (sort_order 6–10) ────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (2,'What is a deadlock in a database?',
       'A query that takes too long to execute',
       'Two transactions each waiting for a lock held by the other, creating a circular wait',
       'A table with no primary key',
       'An index that covers too many columns',
       'B',
       'A deadlock occurs when Transaction A holds a lock that Transaction B needs, while B holds a lock A needs. The database detects this and kills one transaction to break the cycle.',
       6),
    (2,'What does EXPLAIN do in SQL?',
       'Runs a query and explains the result in plain English',
       'Shows the query execution plan chosen by the database planner',
       'Adds comments to a stored procedure',
       'Validates the SQL syntax without executing the query',
       'B',
       'EXPLAIN shows how the database plans to execute a query — which indexes it will use, join order, and estimated row counts. Essential for identifying slow full table scans.',
       7),
    (2,'What is a covering index?',
       'An index that spans the entire table',
       'An index that includes all columns required by a query, so the table itself does not need to be read',
       'A composite index on foreign key columns',
       'An index automatically created by the database',
       'B',
       'A covering index satisfies a query entirely from the index structure, avoiding a second lookup in the actual table. This dramatically speeds up read-heavy queries.',
       8),
    (2,'Which SQL window function assigns a unique sequential integer to each row within a partition?',
       'RANK()','DENSE_RANK()','ROW_NUMBER()','NTILE()',
       'C',
       'ROW_NUMBER() assigns 1, 2, 3, ... to each row within a partition with no gaps or ties. RANK() and DENSE_RANK() handle tied values differently.',
       9),
    (2,'What is the difference between DELETE and TRUNCATE?',
       'DELETE removes the table; TRUNCATE removes rows',
       'TRUNCATE is faster because it removes all rows without logging individual row deletions; DELETE logs each row and supports WHERE',
       'DELETE is DDL; TRUNCATE is DML',
       'There is no difference',
       'B',
       'TRUNCATE is a DDL operation that deallocates data pages — very fast for clearing a table but cannot be rolled back in most databases and does not fire row-level triggers. DELETE is DML, supports WHERE, and logs each row.',
       10)
  `);

  // ── Extra questions for Quiz 3: Web Security (sort_order 6–10) ───────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (3,'What does HSTS (HTTP Strict Transport Security) do?',
       'Encrypts HTTP request bodies automatically',
       'Forces the browser to use HTTPS for a domain for a defined period, even if HTTP is typed',
       'Adds authentication headers to every HTTP request',
       'Blocks third-party cookies',
       'B',
       'HSTS tells the browser: for the next N seconds, always connect to this domain over HTTPS — never HTTP. This defeats SSL stripping attacks where an attacker silently downgrades HTTPS to HTTP.',
       6),
    (3,'What is SSRF (Server-Side Request Forgery)?',
       'A stored XSS attack that targets the server',
       'An attack where the server is tricked into making HTTP requests to internal or unintended external targets',
       'A SQL injection variant that works on NoSQL databases',
       'A CSRF variant targeting API servers',
       'B',
       'In SSRF, an attacker supplies a URL that the server fetches on their behalf — often targeting internal services like AWS metadata endpoint (169.254.169.254), internal APIs, or databases not exposed to the internet.',
       7),
    (3,'Which JWT algorithm should NEVER be accepted by a server?',
       'HS256','RS256','ES256','none',
       'D',
       'The "none" algorithm means no signature — the token is unsigned. If a server accepts alg:none, an attacker can forge any token by simply removing the signature. Always validate and whitelist accepted algorithms.',
       8),
    (3,'What is the purpose of a Content Security Policy (CSP) header?',
       'To enforce HTTPS for all resources',
       'To whitelist which sources scripts, styles, and other resources may be loaded from, blocking injected scripts',
       'To prevent SQL injection attacks',
       'To rate-limit API requests',
       'B',
       'CSP tells the browser which origins are trusted to serve scripts, styles, fonts, etc. An XSS payload injected into your page cannot run if its origin is not in the CSP whitelist, providing a strong second layer of defence.',
       9),
    (3,'What is Broken Object Level Authorisation (BOLA)?',
       'Failing to hash passwords correctly',
       'Allowing users to access other users'' resources by simply changing an object ID in a request',
       'Storing JWT secrets in plaintext',
       'A misconfigured CORS policy',
       'B',
       'BOLA (OWASP API Security #1) occurs when an API endpoint uses user-supplied IDs (e.g. /api/orders/42) without verifying the requesting user owns that object. The fix: always verify ownership server-side, never trust the client.',
       10)
  `);

  // ── Extra questions for Quiz 4: Machine Learning (sort_order 6–10) ───────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (4,'What is the purpose of k-fold cross-validation?',
       'To split the dataset into k equal training sets',
       'To train k different models and pick the best',
       'To produce a more reliable performance estimate by training and evaluating on k different data splits',
       'To reduce the number of features to k',
       'C',
       'k-fold CV splits data into k folds, trains on k-1, tests on the remaining fold, and repeats k times. Averaging the k scores gives a more reliable estimate than a single train/test split, reducing the effect of a lucky or unlucky random split.',
       6),
    (4,'What does PCA (Principal Component Analysis) do?',
       'Classifies data into principal groups',
       'Reduces dimensionality by projecting data onto the directions of greatest variance',
       'Clusters data points using centroids',
       'Increases the number of features to improve accuracy',
       'B',
       'PCA transforms features into a new set of uncorrelated components ordered by variance explained. The top k components capture most information with fewer dimensions, reducing noise, memory, and training time.',
       7),
    (4,'What is gradient descent?',
       'A method of selecting the steepest features for a model',
       'An iterative optimisation algorithm that adjusts model weights in the direction that reduces the loss function',
       'A technique for normalising gradient values in neural networks',
       'A cross-validation strategy for deep learning',
       'B',
       'Gradient descent computes the gradient (partial derivative) of the loss with respect to each weight, then moves each weight a small step in the opposite direction of the gradient, iteratively minimising the loss.',
       8),
    (4,'What does the ROC-AUC score measure?',
       'The accuracy of a regression model',
       'How quickly a model trains',
       'A classifier''s ability to distinguish between positive and negative classes across all decision thresholds',
       'The ratio of precision to recall',
       'C',
       'The ROC curve plots True Positive Rate vs False Positive Rate at every threshold. AUC (Area Under the Curve) summarises this as a single number: 1.0 = perfect, 0.5 = random. Useful when class imbalance makes accuracy misleading.',
       9),
    (4,'What is the difference between bagging and boosting?',
       'Bagging uses deep trees; boosting uses shallow stumps',
       'Bagging trains models in parallel on random subsets to reduce variance; boosting trains sequentially to correct previous errors, reducing bias',
       'Bagging is for classification only; boosting is for regression only',
       'They are the same technique with different names',
       'B',
       'Bagging (e.g. Random Forest) trains many models independently and averages them — reduces variance/overfitting. Boosting (e.g. XGBoost) trains each model to correct the residual errors of the ensemble so far — reduces bias/underfitting.',
       10)
  `);

  // ── Quiz 5: Network Security (10 questions) ───────────────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (5,'At which OSI layer does TLS operate?',
       'Layer 2 (Data Link)','Layer 3 (Network)','Layer 4–5 (Transport/Session)','Layer 7 (Application)',
       'C',
       'TLS sits between the Transport layer (TCP) and the Application layer — it provides a secure channel for application protocols like HTTP, SMTP, and FTP.',
       1),
    (5,'What does a stateful firewall track that a stateless packet filter does not?',
       'Source IP addresses','MAC addresses','TCP connection state','Port numbers',
       'C',
       'A stateful firewall maintains a connection table tracking whether each packet is part of an established TCP session, allowing it to block unsolicited inbound packets that are not part of an existing connection.',
       2),
    (5,'What is ARP spoofing?',
       'Injecting false DNS records into a resolver cache',
       'Sending fake ARP replies to associate the attacker''s MAC with a legitimate IP, enabling a man-in-the-middle attack',
       'Flooding a switch with MAC addresses to disable MAC learning',
       'Redirecting HTTP traffic to a rogue server',
       'B',
       'ARP has no authentication. An attacker can broadcast fake ARP replies saying "I am 192.168.1.1" to poison the ARP caches of other hosts, redirecting their traffic through the attacker''s machine.',
       3),
    (5,'What is a DMZ (Demilitarised Zone) in network architecture?',
       'A VLAN reserved for wireless devices',
       'A network segment between the internet and the internal network that hosts public-facing servers',
       'An encrypted tunnel between two office locations',
       'A firewall rule that blocks all inbound traffic',
       'B',
       'A DMZ places web servers, email servers, and other public-facing services on a separate segment. If one is compromised, the attacker is isolated from the internal corporate network.',
       4),
    (5,'What does IDS stand for, and what is its primary function?',
       'Internet Defence System — blocks malicious traffic','Intrusion Detection System — monitors and alerts on suspicious activity',
       'Internal DNS Server — resolves local hostnames','IP Discovery Service — maps hosts on the network',
       'B',
       'An IDS monitors network traffic or host logs for suspicious patterns and generates alerts. An IPS (Intrusion Prevention System) goes further and can actively block detected threats.',
       5),
    (5,'What is DNS cache poisoning?',
       'Overloading a DNS server with too many queries',
       'Injecting forged DNS records into a resolver''s cache so domain names resolve to attacker-controlled IPs',
       'Encrypting DNS queries to prevent eavesdropping',
       'Registering a domain similar to a legitimate one (typosquatting)',
       'B',
       'DNS has no authentication by default. An attacker can race to respond to a DNS query with a forged answer, poisoning the resolver''s cache and redirecting all users who query that resolver to a malicious server.',
       6),
    (5,'What security improvement does WPA3 provide over WPA2?',
       'Longer SSID names','Simultaneous Authentication of Equals (SAE) replacing the PSK handshake, preventing offline dictionary attacks',
       'Support for more simultaneous clients','Faster throughput via 802.11ax',
       'B',
       'WPA2 PSK 4-way handshake can be captured and subjected to offline brute-force attacks. WPA3''s SAE (Dragonfly handshake) is interactive and zero-knowledge — captured handshakes cannot be cracked offline.',
       7),
    (5,'What is the purpose of network segmentation?',
       'To increase bandwidth between network segments',
       'To divide a network into zones so that a compromise in one zone cannot easily spread to others',
       'To route traffic more efficiently between VLANs',
       'To hide internal IP addresses from external networks using NAT',
       'B',
       'Segmentation limits the blast radius of a breach. If an attacker compromises one segment, they face additional barriers to reach other segments. Critical systems (HR, finance, industrial control) should be on isolated segments.',
       8),
    (5,'What does a SIEM (Security Information and Event Management) system do?',
       'Scans code for vulnerabilities before deployment',
       'Aggregates and correlates logs from across the infrastructure to detect threats and support incident response',
       'Encrypts log files to prevent tampering',
       'Blocks intrusion attempts in real time',
       'B',
       'A SIEM (e.g., Splunk, Microsoft Sentinel) collects logs from firewalls, IDS, servers, and apps. Security teams write detection rules and run threat hunting queries against the centralised data.',
       9),
    (5,'What is a VPN split tunnelling configuration?',
       'A VPN that encrypts only the header, not the payload',
       'A configuration where only traffic to specific destinations routes through the VPN — other traffic uses the normal internet connection',
       'Using two VPN tunnels simultaneously for redundancy',
       'Splitting a site-to-site VPN into two half-tunnels',
       'B',
       'Split tunnelling routes only corporate traffic (e.g., 10.0.0.0/8) through the VPN, while internet traffic goes directly out. This reduces VPN load but means the internet traffic bypasses corporate security controls.',
       10)
  `);

  // ── Quiz 6: Python for Data Science (10 questions) ───────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (6,'Which Python library provides the ndarray for fast numerical computing?',
       'Pandas','Matplotlib','NumPy','SciPy',
       'C',
       'NumPy provides the ndarray — a fast, memory-efficient multi-dimensional array implemented in C. It is the foundation of virtually every Python data science library including Pandas and scikit-learn.',
       1),
    (6,'What does the Pandas groupby() operation do?',
       'Sorts a DataFrame by one or more columns',
       'Splits a DataFrame into groups, applies an aggregation function to each group, and combines the results',
       'Joins two DataFrames on a common column',
       'Removes duplicate rows from a DataFrame',
       'B',
       'groupby() implements the split-apply-combine pattern: split rows into groups by a column value, apply a function (sum, mean, count, custom), and combine into a new DataFrame.',
       2),
    (6,'What is data leakage in machine learning?',
       'Training data accidentally deleted during preprocessing',
       'Accidentally including future or target information during training, producing inflated and unreliable performance metrics',
       'Sensitive data being logged to a public server',
       'Features with missing values causing errors during model training',
       'B',
       'Data leakage occurs when information from the test set or future data influences training — e.g., scaling the entire dataset before the train/test split so the scaler "sees" test data. Always fit preprocessors on training data only.',
       3),
    (6,'What is feature scaling, and why is it important?',
       'Reducing the number of features using PCA',
       'Normalising feature ranges so no feature dominates the model due to its larger numerical magnitude',
       'Selecting only the most correlated features for training',
       'Converting categorical features to numerical ones',
       'B',
       'Algorithms like k-NN, SVM, and gradient descent are sensitive to feature magnitudes. A salary column (0–100,000) would dominate an age column (0–100) without scaling. Standardisation (z-score) or min-max normalisation fix this.',
       4),
    (6,'What does NumPy broadcasting allow?',
       'Sending NumPy arrays over a network socket',
       'Performing arithmetic operations on arrays of different shapes without explicit loops, by automatically expanding smaller arrays',
       'Distributing computation across multiple CPU cores',
       'Converting Python lists to NumPy arrays',
       'B',
       'Broadcasting allows, e.g., adding a (3,) row vector to every row of a (100, 3) matrix without a Python for-loop. NumPy stretches the smaller array conceptually — the actual operation runs in optimised C.',
       5),
    (6,'What is the purpose of a train/test split?',
       'To reduce training time by using less data',
       'To evaluate how well a model generalises to unseen data by holding out a portion that was never seen during training',
       'To balance the classes in an imbalanced dataset',
       'To create two copies of the data for backup',
       'B',
       'If you evaluate on the same data you trained on, the model appears perfect even if it just memorised the training set. The held-out test set simulates new unseen data.',
       6),
    (6,'Which chart type is most appropriate for visualising the distribution of a single numerical variable?',
       'Bar chart','Scatter plot','Histogram','Line chart',
       'C',
       'A histogram bins continuous values into ranges and counts how many observations fall in each bin, showing the shape (normal, skewed, bimodal) of the distribution.',
       7),
    (6,'What does the Pandas .fillna() method do?',
       'Removes rows with missing values','Fills missing (NaN) values with a specified value or strategy','Renames columns with null names','Replaces infinite values with NaN',
       'B',
       'NaN (Not a Number) is Pandas'' representation of missing data. .fillna(value) replaces all NaN cells with a constant, mean, median, or forward/backward fill.',
       8),
    (6,'What does vectorisation mean in the context of NumPy?',
       'Converting string columns to numerical vectors',
       'Replacing Python for-loops with array operations that execute in optimised C, orders of magnitude faster',
       'Representing sparse matrices as dense vectors',
       'Normalising data to unit vectors',
       'B',
       'Pure Python loops process one element at a time with interpreter overhead. NumPy vectorised operations process entire arrays in compiled C code — often 100–1000× faster for numerical tasks.',
       9),
    (6,'What is the scikit-learn Pipeline object used for?',
       'Running multiple ML models in parallel','Chaining preprocessing steps and a model into a single object to prevent data leakage during cross-validation',
       'Downloading datasets from the internet','Visualising the model training process',
       'B',
       'A Pipeline ensures that fit() is called only on training data and transform() is applied consistently. Without it, fitting a scaler on all data before CV splits leaks test set statistics into training.',
       10)
  `);

  // ── Quiz 7: Cloud Computing & AWS (10 questions) ─────────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (7,'What does IAM stand for in AWS, and what is its purpose?',
       'Internet Access Management — controls network traffic','Identity and Access Management — controls who can do what in your AWS account',
       'Instance Allocation Monitor — tracks EC2 usage','Integrated Application Manager — deploys applications',
       'B',
       'Every API call in AWS is authorised by IAM. You create users, groups, and roles with attached policies that grant (or deny) specific permissions on specific resources.',
       1),
    (7,'What is the principle of least privilege in cloud security?',
       'Giving all developers admin access for productivity',
       'Granting only the minimum permissions required for a task — nothing more',
       'Using the cheapest AWS instance types',
       'Keeping all data in one region for simplicity',
       'B',
       'The most common cause of cloud data breaches is over-privileged IAM entities. Least privilege limits the blast radius — a compromised credential can only access what it needed, not the entire account.',
       2),
    (7,'What AWS service provides scalable, durable object storage?',
       'EBS (Elastic Block Store)','RDS (Relational Database Service)','S3 (Simple Storage Service)','EFS (Elastic File System)',
       'C',
       'S3 stores objects (files) in buckets. It is designed for 99.999999999% (11 nines) durability, scales to exabytes, and is used for static websites, backups, data lakes, and application file storage.',
       3),
    (7,'What does an AWS Security Group do?',
       'Scans EC2 instances for malware','Acts as a stateful virtual firewall controlling inbound and outbound traffic to EC2 instances',
       'Groups IAM users for permission management','Monitors AWS costs and sends budget alerts',
       'B',
       'Security Groups are stateful — inbound rules allow traffic, and return traffic is automatically allowed. All traffic is denied by default until you add an allow rule. They work at the instance level, not the subnet level.',
       4),
    (7,'What is AWS Lambda?',
       'A serverless compute service that runs code in response to events without you provisioning servers',
       'A managed Kubernetes service','A NoSQL database','A content delivery network',
       'A',
       'Lambda runs your function only when triggered (HTTP request, S3 upload, schedule, etc.), scales from zero to thousands of concurrent executions automatically, and charges per 100ms of execution time.',
       5),
    (7,'What is the difference between a public subnet and a private subnet in a VPC?',
       'Public subnets are faster; private subnets are more secure',
       'Public subnets have a route to an Internet Gateway and can have public IPs; private subnets do not and use a NAT Gateway for outbound traffic',
       'Public subnets run web servers; private subnets run databases by convention only',
       'There is no functional difference — the terms are cosmetic',
       'B',
       'Resources in a public subnet (e.g., load balancers, web servers) can receive inbound internet traffic. Private subnet resources (e.g., databases, app servers) are not directly reachable from the internet — they initiate outbound connections via NAT Gateway.',
       6),
    (7,'What does Multi-AZ deployment provide in AWS RDS?',
       'Lower cost by spreading load','Automatic failover to a synchronous standby in a second Availability Zone if the primary fails',
       'Read scaling through replicas','Automated database schema migrations',
       'B',
       'Multi-AZ maintains a synchronous replica in a different AZ. If the primary fails (hardware fault, AZ outage), RDS automatically fails over to the standby — typically within 1–2 minutes — with no data loss.',
       7),
    (7,'What is an AMI (Amazon Machine Image)?',
       'An auto-scaling policy for EC2','A template containing the OS, software configuration, and data used to launch EC2 instances',
       'An IAM permission policy for machine learning workloads','A monitoring agent installed on EC2 instances',
       'B',
       'AMIs are the blueprints for EC2 instances. You can create a custom AMI from a configured instance and use it to launch identical copies quickly — essential for auto-scaling and consistent deployments.',
       8),
    (7,'What is the shared responsibility model in cloud computing?',
       'The cloud provider is responsible for all security','The customer is responsible for all security',
       'The cloud provider secures the infrastructure; the customer is responsible for security of what runs on it',
       'Security responsibilities are negotiated case by case',
       'C',
       'AWS secures the physical infrastructure, hypervisor, and managed service internals. You are responsible for OS patching, IAM configuration, network settings, application security, and data encryption.',
       9),
    (7,'What is auto-scaling in AWS?',
       'Automatically upgrading EC2 instance types','Automatically adding or removing EC2 instances based on demand metrics to maintain performance and reduce cost',
       'Automatically applying OS patches to EC2 instances','Automatically backing up RDS databases',
       'B',
       'Auto Scaling Groups monitor CloudWatch metrics (CPU utilisation, request count). When demand rises, new instances launch from an AMI. When it drops, excess instances terminate. You pay only for what you use.',
       10)
  `);

  // ── Quiz 8: Full Stack Web Development (10 questions) ────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (8,'What HTTP method is conventionally used to fully replace a resource?',
       'POST','PATCH','PUT','DELETE',
       'C',
       'PUT replaces the entire resource with the supplied body. PATCH updates only the specified fields. POST creates a new resource. Using the correct method matters for REST semantics and client caching behaviour.',
       1),
    (8,'What is a middleware function in Express.js?',
       'A function that compresses the final HTML response',
       'A function with (req, res, next) signature that can inspect/modify the request, send a response, or call next() to pass control to the next handler',
       'A helper library for database queries','A route handler for the root path',
       'B',
       'Middleware runs in a pipeline. Common examples: body-parser (parses JSON), cors(), authentication checks, logging. Calling next() passes control; not calling it ends the pipeline.',
       2),
    (8,'What is a JWT (JSON Web Token) and what are its three parts?',
       'A session cookie containing user preferences; split into header, data, expiry',
       'A signed token for stateless authentication, containing: Header (algorithm), Payload (claims like user ID), and Signature (verifies integrity)',
       'An encrypted password token; split into salt, hash, and version',
       'A database connection token; split into host, port, and credentials',
       'B',
       'JWTs are Base64-encoded JSON: header.payload.signature. The server verifies the signature cryptographically — no database lookup needed. Keep them short-lived; store in httpOnly cookies, not localStorage.',
       3),
    (8,'What does bcrypt do and why is it used for passwords instead of SHA-256?',
       'bcrypt compresses passwords; SHA-256 encrypts them',
       'bcrypt is a deliberately slow, salt-generating password hash resistant to brute-force; SHA-256 is too fast — a GPU can compute 10 billion SHA-256 hashes per second',
       'bcrypt is reversible for password recovery; SHA-256 is not',
       'There is no meaningful difference — both are equally secure for passwords',
       'B',
       'Password hashing must be slow by design. bcrypt''s cost factor makes each hash take ~100ms, limiting an attacker to ~10 guesses/second instead of billions. It also generates a unique salt automatically.',
       4),
    (8,'What does CORS (Cross-Origin Resource Sharing) control?',
       'Which HTTP methods a server supports',
       'Which cross-origin domains are allowed to make requests to an API via browser JavaScript',
       'How compressed responses are encoded','Which cookies are sent with every request',
       'B',
       'Browsers enforce the Same-Origin Policy — JavaScript on site-A cannot call APIs on site-B without CORS headers. The server opts in by sending Access-Control-Allow-Origin headers listing trusted origins.',
       5),
    (8,'What is the difference between authentication and authorisation?',
       'They are the same concept with different names',
       'Authentication verifies WHO you are (login); authorisation verifies WHAT you are allowed to do (permissions)',
       'Authentication is for APIs; authorisation is for web pages',
       'Authentication uses passwords; authorisation uses tokens',
       'B',
       'You must authenticate before you can be authorised. Confusing the two is a common security mistake — e.g., checking if a user is logged in (auth) but not checking if they own the resource they are accessing (authz).',
       6),
    (8,'What is a database connection pool?',
       'A backup copy of the database','A cache of reusable database connections that avoids the overhead of opening a new TCP connection per request',
       'A query result cache','A pool of read replicas for load balancing',
       'B',
       'Opening a new DB connection is expensive (~20–100ms). A pool (e.g., 10 connections) keeps them open and reuses them across requests, drastically improving throughput on a web server.',
       7),
    (8,'Which HTTP status code should a REST API return when a resource is successfully created?',
       '200 OK','201 Created','204 No Content','202 Accepted',
       'B',
       '201 Created signals that the POST request succeeded and a new resource was created. The response body typically includes the created object. Using 200 for creation is common but semantically incorrect.',
       8),
    (8,'What is environment variable management and why does it matter?',
       'Managing the PATH variable on developer machines',
       'Storing configuration values (DB URLs, API keys, JWT secrets) outside source code in .env files or hosting platform config to prevent secrets being committed to git',
       'Setting memory limits for Node.js processes','Configuring OS-level environment for CI pipelines',
       'B',
       'Committing secrets to git is one of the most common security incidents. Even in a "private" repo, secrets are exposed to everyone with access and persist in git history forever. Use dotenv locally; use the hosting platform''s config in production.',
       9),
    (8,'What is the N+1 query problem?',
       'Running N queries to create a single record across N tables',
       'Fetching a list of N records and then running a separate database query for each one, resulting in N+1 total queries instead of 1',
       'Having more database indexes than table columns','A query that returns N+1 rows due to a faulty JOIN',
       'B',
       'Example: fetch 100 users (1 query), then for each user fetch their posts (100 queries) = 101 queries. Fix with a single JOIN or ORM eager loading. The N+1 problem is the most common cause of slow API endpoints.',
       10)
  `);

  // ── Quiz 9: React & Modern JavaScript (10 questions) ─────────────────────────
  await pool.query(`
    INSERT IGNORE INTO quiz_questions (quiz_id, question, option_a, option_b, option_c, option_d, correct_answer, explanation, sort_order) VALUES
    (9,'What is JSX in React?',
       'A JavaScript XML parser','A syntax extension that lets you write HTML-like code inside JavaScript, compiled to React.createElement() calls',
       'A CSS-in-JS library','A JSON serialisation format for components',
       'B',
       'JSX is syntactic sugar. <div className="card">Hello</div> compiles to React.createElement("div", {className: "card"}, "Hello"). Babel/Vite transpiles JSX before it runs in the browser.',
       1),
    (9,'What does the useEffect hook do?',
       'Creates a new state variable','Runs a side effect (data fetching, subscriptions, DOM manipulation) after the component renders, with optional cleanup',
       'Memoises a function reference between renders','Creates a context provider',
       'B',
       'useEffect replaces componentDidMount, componentDidUpdate, and componentWillUnmount. The dependency array controls when it re-runs. Return a cleanup function to cancel subscriptions or timers on unmount.',
       2),
    (9,'What is the virtual DOM in React?',
       'A DOM stored in a database','An in-memory JavaScript representation of the UI that React uses to calculate the minimum set of real DOM updates needed',
       'A hidden iframe used for rendering','A server-side copy of the DOM for SSR',
       'B',
       'When state changes, React re-renders components into a new virtual DOM tree, diffs it against the previous one, and applies only the changed operations to the actual DOM — far more efficient than re-rendering everything.',
       3),
    (9,'What does useState return?',
       'The current state value only',
       'An array of [currentStateValue, setterFunction] — the setter triggers a re-render when called with a new value',
       'A mutable ref object','A Promise that resolves to the state value',
       'B',
       'const [count, setCount] = useState(0). Calling setCount(1) tells React the state changed, causing the component to re-render with the new value. Direct mutation (count = 1) does NOT trigger re-render.',
       4),
    (9,'What is a closure in JavaScript?',
       'A syntax for immediately invoked functions',
       'A function that retains access to the variables from its outer (enclosing) scope even after that outer function has returned',
       'A method for closing WebSocket connections','A design pattern for encapsulating class methods',
       'B',
       'Closures are fundamental to JS: event handlers, React hooks (useState captures state via closure), module patterns, and factory functions all rely on closures. They enable data encapsulation without classes.',
       5),
    (9,'What does the JavaScript spread operator (...) do?',
       'Defines rest parameters in function signatures only',
       'Expands an iterable (array/object) into individual elements — enables shallow copying and merging without mutation',
       'Converts a string to a character array','Creates a generator function',
       'B',
       'const newArr = [...arr1, ...arr2] merges arrays. const newObj = {...obj, key: val} shallow-copies and overrides a key. Used heavily in React to update state immutably without mutating the original object.',
       6),
    (9,'What is the JavaScript event loop?',
       'A built-in loop for handling DOM click events',
       'The mechanism that allows single-threaded JS to handle asynchronous operations by moving completed async callbacks from the task queue to the call stack when it is empty',
       'A loop that runs every frame for animations','A Node.js-specific feature not present in browsers',
       'B',
       'JS is single-threaded. When you fetch() data, the browser handles the network I/O separately. When done, the callback sits in the task queue. The event loop moves it to the call stack only when the stack is empty — hence async operations never block the UI.',
       7),
    (9,'What is React Context used for?',
       'Managing component-level local state',
       'Sharing state across multiple components in a tree without passing props through every intermediate level (prop drilling)',
       'Fetching data from an API','Replacing all useState hooks in a large application',
       'B',
       'Context provides a way to pass values (theme, auth user, locale) to deeply nested components without explicit prop passing at every level. Use it for truly global state; for complex state logic, consider useReducer or a state library.',
       8),
    (9,'What is destructuring assignment in JavaScript?',
       'Removing properties from an object permanently',
       'A syntax for extracting values from arrays or properties from objects into distinct variables in a single statement',
       'Converting a class instance to a plain object','A method for deep-cloning objects',
       'B',
       'const {name, age} = user extracts object properties. const [first, second] = arr extracts array items. Destructuring is used everywhere in React: const [state, setState] = useState(), function Header({title, user}) {}.',
       9),
    (9,'What problem does async/await solve compared to raw Promises?',
       'It makes JavaScript multi-threaded',
       'It makes asynchronous code read like synchronous code, eliminating nested .then() chains (callback hell) while still being non-blocking',
       'It eliminates the need for error handling in async operations','It speeds up network requests',
       'B',
       'async/await is syntactic sugar over Promises. await pauses the async function until the Promise resolves (without blocking the thread). try/catch handles rejections naturally. The underlying event loop mechanics are unchanged.',
       10)
  `);

  console.log('All quizzes seeded successfully.');
  process.exit(0);
})().catch(err => { console.error(err); process.exit(1); });
